POST http://localhost:8080/api/v1/trans/user
Content-Type: application/json

{
"nom": "Salah",
  "prenom": "moh",
  "adresse": "1 rue de test, 44300 nantes",
  "email": "moh.salah@test.com",
  "username": "mohsalah",
  "password": "password",
  "telephone": "12345678"
}

###

POST http://localhost:8080/api/v1/trans/user
Content-Type: application/json

{
  "nom": "firmino",
  "prenom": "Bobby",
  "adresse": "2 rue de test, 44300 nantes",
  "email": "bobby.firmino@test.com",
  "username": "bobbyFirm",
  "password": "password",
  "telephone": "12345678"
}

###

PUT http://localhost:8080/api/v1/trans/user/admin
Content-Type: application/x-www-form-urlencoded

email=bobby.firmino@test.com

###

GET http://localhost:8080/api/v1/trans/users
Authorization: Basic bobby.firmino@test.com password

###

PUT http://localhost:8080/api/v1/trans/user/2
Content-Type: application/x-www-form-urlencoded

prenom=Roberto

###

PUT http://localhost:8080/api/v1/trans/user/2
Content-Type: application/x-www-form-urlencoded

nom=Firmino

###

DELETE http://localhost:8080/api/v1/trans/user/1

###

POST http://localhost:8080/api/v1/trans/abonnement/mohsalah
Content-Type: application/x-www-form-urlencoded

type=mensuel

###

POST http://localhost:8080/api/v1/trans/abonnement/mohsalah
Content-Type: application/x-www-form-urlencoded

type=annuel

###

POST http://localhost:8080/api/v1/trans/abonnement/mohsalah
Content-Type: application/x-www-form-urlencoded

type=annuelle

###

GET http://localhost:8080/api/v1/trans/abonnements/mohsalah
Accept: application/json

###

POST http://localhost:8080/api/v1/trans/titreTransport/mohsalah
Content-Type: application/x-www-form-urlencoded

type=1H

###

POST http://localhost:8080/api/v1/trans/titreTransport/mohsalah
Content-Type: application/x-www-form-urlencoded

type=24H

###

PUT http://localhost:8080/api/v1/trans/titreTransport/validation/mohsalah
Content-Type: application/x-www-form-urlencoded

id=6092923a4044402c1446ec79

###

GET http://localhost:8080/api/v1/trans/titreTransports/mohsalah
Accept: application/json

###
